[package]
name = "final-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "1.0.0"
actix-web = "4.0"
actix-cors = "0.6"
actix-http = "3.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
ethers = { version = "2.0" }
serde = { version = "1.0", features = ["derive"] }
async-std= {version = "1.6",features = ["attributes"]}
mysql = "20.1"
anyhow = "1.0"
